DEBUG:websockets.protocol:client - event = data_received(<275 bytes>)
DEBUG:websockets.protocol:client < Frame(fin=True, opcode=2, data=b'{"marketUpdate":{"market":{"exchangeId":"27","currencyPairId":"231","marketId":"579"},"tradesUpdate":{"trades":[{"externalId":"260543220","timestamp":"1585769328","timestampNano":"1585769328501000000","priceStr":"6168.56","amountStr":"0.274443","orderSide":"BUYSIDE"}]}}}', rsv1=False, rsv2=False, rsv3=False)
{'marketUpdate': {'market': {'currencyPairId': 231,
                             'exchangeId': 27,
                             'marketId': 579},
                  'tradesUpdate': {'trades': [{'amount': Decimal128('0.274443'),
                                               'orderSide': 'BUYSIDE',
                                               'price': Decimal128('6168.56'),
                                               'timestamp': 1585769328,
                                               'timestampNano': 1585769328501000000}]}}}
DEBUG:__main__:doc_id: 5e84eb70114fc94cd3dedf81
DEBUG:websockets.protocol:client > Frame(fin=True, opcode=9, data=b'\xb3\xd5\xef9', rsv1=False, rsv2=False, rsv3=False)
DEBUG:websockets.protocol:client ! timed out waiting for pong
DEBUG:websockets.protocol:client ! failing OPEN WebSocket connection with code 1011
DEBUG:websockets.protocol:client - state = CLOSING
DEBUG:websockets.protocol:client > Frame(fin=True, opcode=8, data=b'\x03\xf3', rsv1=False, rsv2=False, rsv3=False)
DEBUG:websockets.protocol:client ! timed out waiting for TCP close
DEBUG:websockets.protocol:client x closing TCP connection
DEBUG:websockets.protocol:client ! timed out waiting for TCP close
DEBUG:websockets.protocol:client x aborting TCP connection
DEBUG:websockets.protocol:client - event = connection_lost(None)
DEBUG:websockets.protocol:client - state = CLOSED
DEBUG:websockets.protocol:client x code = 1006, reason = [no reason]
DEBUG:websockets.protocol:client - aborted pending ping: b3d5ef39
Traceback (most recent call last):
  File "/home/hunter/.local/share/virtualenvs/mongotrades-wwdAjhzG/lib/python3.7/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/hunter/.local/share/virtualenvs/mongotrades-wwdAjhzG/lib/python3.7/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/hunter/.local/share/virtualenvs/mongotrades-wwdAjhzG/lib/python3.7/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/hunter/.local/share/virtualenvs/mongotrades-wwdAjhzG/lib/python3.7/site-packages/websockets/protocol.py", line 1051, in read_frame
    extensions=self.extensions,
  File "/home/hunter/.local/share/virtualenvs/mongotrades-wwdAjhzG/lib/python3.7/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.7/asyncio/streams.py", line 679, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "mongotrades.py", line 102, in <module>
    consume(api_key=config['cryptowatch']['api'], sub_msg=subscription_message))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "mongotrades.py", line 88, in consume
    await consumer_handler(websocket)
  File "mongotrades.py", line 76, in consumer_handler
    async for message in websocket:
  File "/home/hunter/.local/share/virtualenvs/mongotrades-wwdAjhzG/lib/python3.7/site-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/home/hunter/.local/share/virtualenvs/mongotrades-wwdAjhzG/lib/python3.7/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/hunter/.local/share/virtualenvs/mongotrades-wwdAjhzG/lib/python3.7/site-packages/websockets/protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason